In [1]:
!pip install numpy


In [2]:
import numpy as np


# CREATE

In [4]:
data=np.random.rand(2,3,4)#random array
zeroes=np.zeros((2,2,2))#array of zeros
full=np.full((2,2,2),7)#array of 7's
ones=np.ones((2,2,2))#array of ones


In [5]:
data

array([[[0.6570936 , 0.3477199 , 0.33336763, 0.73350875],
        [0.09672325, 0.30882683, 0.89071918, 0.49215522],
        [0.79312167, 0.21698541, 0.61006965, 0.72583475]],

       [[0.73102646, 0.56149379, 0.18943447, 0.81572932],
        [0.05283257, 0.70673672, 0.18371749, 0.06018925],
        [0.38927535, 0.65983723, 0.66414771, 0.56534359]]])

In [6]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [7]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [8]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [9]:
arr=np.array([[1,2,3,4],[2,3,4,5]])

In [10]:
arr

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [11]:
type(arr)

numpy.ndarray

# READ

In [15]:
shape=data.shape

size=data.size#no of elements

types=data.dtype#datatype of elements

In [16]:
shape

(2, 3, 4)

In [17]:
size

24

In [18]:
types

dtype('float64')

In [22]:
arr=data[0]
slicer=data[0:2]
slicer1=data[0][0]
reverse=data[-1]
singlevel=data[0][0][0]

In [20]:
arr

array([[0.6570936 , 0.3477199 , 0.33336763, 0.73350875],
       [0.09672325, 0.30882683, 0.89071918, 0.49215522],
       [0.79312167, 0.21698541, 0.61006965, 0.72583475]])

In [21]:
slicer

array([[[0.6570936 , 0.3477199 , 0.33336763, 0.73350875],
        [0.09672325, 0.30882683, 0.89071918, 0.49215522],
        [0.79312167, 0.21698541, 0.61006965, 0.72583475]],

       [[0.73102646, 0.56149379, 0.18943447, 0.81572932],
        [0.05283257, 0.70673672, 0.18371749, 0.06018925],
        [0.38927535, 0.65983723, 0.66414771, 0.56534359]]])

In [23]:
slicer1


array([0.6570936 , 0.3477199 , 0.33336763, 0.73350875])

In [24]:
reverse

array([[0.73102646, 0.56149379, 0.18943447, 0.81572932],
       [0.05283257, 0.70673672, 0.18371749, 0.06018925],
       [0.38927535, 0.65983723, 0.66414771, 0.56534359]])

In [25]:
singlevel

0.6570935989904122

# UPDATE

In [26]:
list1=np.random.rand(10)
list2=np.random.rand(10)

In [27]:
list1

array([0.22622781, 0.47224429, 0.62798007, 0.18306165, 0.81043911,
       0.99037515, 0.08686433, 0.95130209, 0.37554917, 0.4792316 ])

In [28]:
list2

array([0.23790943, 0.84040749, 0.34340609, 0.94583449, 0.91373231,
       0.81960351, 0.56265919, 0.15085964, 0.1821996 , 0.50585843])

In [29]:
add=np.add(list1,list2)
sub=np.subtract(list1,list2)
div=np.divide(list1,list2)
mul=np.multiply(list1,list2)
dot=np.dot(list1,list2)#dot product=


In [30]:
add

array([0.46413723, 1.31265178, 0.97138616, 1.12889614, 1.72417142,
       1.80997865, 0.64952353, 1.10216173, 0.55774877, 0.98509004])

In [31]:
sub

array([-0.01168162, -0.3681632 ,  0.28457399, -0.76277284, -0.10329319,
        0.17077164, -0.47579486,  0.80044244,  0.19334957, -0.02662683])

In [32]:
div

array([0.95089888, 0.56192299, 1.82868067, 0.19354512, 0.88695464,
       1.20835885, 0.15438179, 6.30587521, 2.06119645, 0.94736308])

In [33]:
mul

array([0.05382173, 0.39687764, 0.21565218, 0.17314602, 0.7405244 ,
       0.81171494, 0.04887502, 0.14351309, 0.06842491, 0.24242335])

In [34]:
dot

2.8949732736558182

In [46]:
#SAPLEM (maths funcs)
sqrt=np.sqrt(25)
ab1=np.abs(-2)
ab2=np.abs(2)
pwr=np.power(3,4)
log=np.log(10)
exp=np.exp([2,4])
mins=np.min(list1)
maxs=np.max(list1)

In [36]:
sqrt

5.0

In [37]:
ab1

2

In [47]:
ab2

2

In [39]:
pwr

81

In [40]:
log

2.302585092994046

In [45]:
exp

array([ 7.3890561 , 54.59815003])

In [42]:
mins

0.08686433279701411

In [43]:
maxs

0.9903751455092626

In [48]:
data

array([[[0.6570936 , 0.3477199 , 0.33336763, 0.73350875],
        [0.09672325, 0.30882683, 0.89071918, 0.49215522],
        [0.79312167, 0.21698541, 0.61006965, 0.72583475]],

       [[0.73102646, 0.56149379, 0.18943447, 0.81572932],
        [0.05283257, 0.70673672, 0.18371749, 0.06018925],
        [0.38927535, 0.65983723, 0.66414771, 0.56534359]]])

In [49]:
data[0][0][0]=7

In [50]:
data

array([[[7.        , 0.3477199 , 0.33336763, 0.73350875],
        [0.09672325, 0.30882683, 0.89071918, 0.49215522],
        [0.79312167, 0.21698541, 0.61006965, 0.72583475]],

       [[0.73102646, 0.56149379, 0.18943447, 0.81572932],
        [0.05283257, 0.70673672, 0.18371749, 0.06018925],
        [0.38927535, 0.65983723, 0.66414771, 0.56534359]]])

In [51]:
data.sort()

In [52]:
data

array([[[0.33336763, 0.3477199 , 0.73350875, 7.        ],
        [0.09672325, 0.30882683, 0.49215522, 0.89071918],
        [0.21698541, 0.61006965, 0.72583475, 0.79312167]],

       [[0.18943447, 0.56149379, 0.73102646, 0.81572932],
        [0.05283257, 0.06018925, 0.18371749, 0.70673672],
        [0.38927535, 0.56534359, 0.65983723, 0.66414771]]])

In [53]:
print(data.shape)

(2, 3, 4)


In [54]:
data=data.reshape((2,2,-1))#-1 means it would take a random value for that particular indice in the shape
data.shape

(2, 2, 6)

In [56]:
zeroes=np.zeros((8))
zeroes


array([0., 0., 0., 0., 0., 0., 0., 0.])

In [57]:
zeroes=np.append(zeroes,[3,4])#adds the set of values in the end
zeroes

array([0., 0., 0., 0., 0., 0., 0., 0., 3., 4.])

In [63]:
#run two times so two 1's
zeroes=np.insert(zeroes,2,1)#insert(array name,position,value)
zeroes

array([0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 3., 4.])

# DELETE


In [65]:
data

array([[[0.33336763, 0.3477199 , 0.73350875, 7.        , 0.09672325,
         0.30882683],
        [0.49215522, 0.89071918, 0.21698541, 0.61006965, 0.72583475,
         0.79312167]],

       [[0.18943447, 0.56149379, 0.73102646, 0.81572932, 0.05283257,
         0.06018925],
        [0.18371749, 0.70673672, 0.38927535, 0.56534359, 0.65983723,
         0.66414771]]])

In [66]:
np.delete(data,0, axis=1)#delete(array,value,axis(1 for row 0 for column))

array([[[0.49215522, 0.89071918, 0.21698541, 0.61006965, 0.72583475,
         0.79312167]],

       [[0.18371749, 0.70673672, 0.38927535, 0.56534359, 0.65983723,
         0.66414771]]])

In [70]:
np.delete(data,0,axis=0)

array([[[0.18943447, 0.56149379, 0.73102646, 0.81572932, 0.05283257,
         0.06018925],
        [0.18371749, 0.70673672, 0.38927535, 0.56534359, 0.65983723,
         0.66414771]]])

In [67]:
np.save("new array",data)

In [68]:
test=np.load("new array.npy")

In [69]:
test

array([[[0.33336763, 0.3477199 , 0.73350875, 7.        , 0.09672325,
         0.30882683],
        [0.49215522, 0.89071918, 0.21698541, 0.61006965, 0.72583475,
         0.79312167]],

       [[0.18943447, 0.56149379, 0.73102646, 0.81572932, 0.05283257,
         0.06018925],
        [0.18371749, 0.70673672, 0.38927535, 0.56534359, 0.65983723,
         0.66414771]]])